version: "3.7"

services:
  app:
    build:
      args:
        uid: ${UID}
      context: .
    image: excypher-dev:latest
    volumes:
      - $PWD:/excypher
    working_dir: /excypher
    environment:
      NEO4J_HOST: neo4j
      NEO4J_HTTP_PORT: 7474
      NEO4J_PORT: 7687
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.2
    environment:
      NEO4J_AUTH: none
    platform: linux/amd64
